business_central:
  environments:
    - code: PROD
      name: Production
      type: production
    - code: UAT
      name: UAT
      type: sandbox
    - code: TEST
      name: Test
      type: sandbox

  companies:
    - code: EMPRESA01
      name: Empresa 01
      language: pt-PT
    - code: EMPRESA02
      name: Empresa 02
      language: pt-PT
    - code: EMPRESA03
      name: Empresa 03
      language: pt-PT
